from django.urls import path

from apps.doctors import views as doctor_views
from apps.nurses import views as nurse_views
from apps.patients import views as patient_views

from . import spec_alias_views as alias_views


urlpatterns = [
    path("admissions/", patient_views.AdmissionListCreateView.as_view()),
    path("admissions/<uuid:pk>/", patient_views.AdmissionDetailView.as_view()),
    path("admissions/<uuid:pk>/status/", patient_views.AdmissionStatusView.as_view()),
    path("admissions/<uuid:pk>/discharge/", patient_views.AdmissionDischargeView.as_view()),
    path("admissions/<uuid:pk>/transfer/", patient_views.AdmissionTransferView.as_view()),
    path("appointments/", patient_views.AppointmentListCreateView.as_view()),
    path("appointments/<uuid:pk>/", patient_views.AppointmentDetailView.as_view()),
    path("appointments/<uuid:pk>/status/", patient_views.AppointmentStatusView.as_view()),
    path("wards/", patient_views.WardListView.as_view()),
    path("wards/<uuid:ward_id>/patients/", alias_views.WardPatientListAliasView.as_view()),
    path("beds/", patient_views.BedListView.as_view()),
    path("beds/<uuid:pk>/", patient_views.BedDetailView.as_view()),
    path("beds/<uuid:pk>/status/", patient_views.BedStatusView.as_view()),
    path("queue/", patient_views.QueueListCreateView.as_view()),
    path("queue/stats/", patient_views.QueueStatsView.as_view()),
    path("queue/<uuid:pk>/status/", patient_views.QueueStatusView.as_view()),
    path("encounters/", doctor_views.EncounterListCreateView.as_view()),
    path("encounters/<uuid:pk>/", doctor_views.EncounterDetailView.as_view()),
    path("encounters/<uuid:pk>/sign/", doctor_views.EncounterSignView.as_view()),
    path("encounters/<uuid:pk>/amend/", doctor_views.EncounterAmendView.as_view()),
    path("orders/", doctor_views.OrderListCreateView.as_view()),
    path("orders/<uuid:pk>/", doctor_views.OrderDetailView.as_view()),
    path("prescriptions/", doctor_views.PrescriptionListCreateView.as_view()),
    path("prescriptions/<uuid:pk>/", doctor_views.PrescriptionDetailView.as_view()),
    path("prescriptions/<uuid:pk>/status/", doctor_views.PrescriptionStatusView.as_view()),
    path("diagnoses/", doctor_views.DiagnosisListCreateView.as_view()),
    path("diagnoses/<uuid:pk>/", doctor_views.DiagnosisDetailView.as_view()),
    path("icd10/search/", doctor_views.ICD10SearchView.as_view()),
    path("referrals/", doctor_views.ReferralListCreateView.as_view()),
    path("referrals/<uuid:pk>/", doctor_views.ReferralDetailView.as_view()),
    path("referrals/<uuid:pk>/status/", doctor_views.ReferralStatusView.as_view()),
    path("results/<uuid:pk>/review/", doctor_views.ResultReviewView.as_view()),
    path("doctors/<uuid:pk>/results/", doctor_views.DoctorResultsInboxView.as_view()),
    path("patients/<uuid:patient_pk>/encounters/", alias_views.PatientEncounterListAliasView.as_view()),
    path("patients/<uuid:patient_pk>/orders/", alias_views.PatientOrderListAliasView.as_view()),
    path("patients/<uuid:patient_pk>/prescriptions/", alias_views.PatientPrescriptionListAliasView.as_view()),
    path("patients/<uuid:patient_pk>/diagnoses/", alias_views.PatientDiagnosisListAliasView.as_view()),
    path("patients/<uuid:patient_pk>/referrals/", alias_views.PatientReferralListAliasView.as_view()),
    path("patients/<uuid:patient_id>/medication-profile/", alias_views.PatientMedicationProfileAliasView.as_view()),
    path("patients/<uuid:patient_id>/vitals/", alias_views.PatientVitalsAliasView.as_view()),
    path("patients/<uuid:patient_id>/vitals/latest/", nurse_views.VitalsLatestView.as_view()),
    path("patients/<uuid:patient_id>/io/", alias_views.PatientIOAliasView.as_view()),
    path("patients/<uuid:patient_id>/pain/", alias_views.PatientPainAliasView.as_view()),
    path("patients/<uuid:patient_id>/mar/", alias_views.PatientMARAliasView.as_view()),
    path("patients/<uuid:patient_id>/nursing-notes/", alias_views.PatientNursingNotesAliasView.as_view()),
    path("patients/<uuid:patient_id>/wounds/", alias_views.PatientWoundsAliasView.as_view()),
    path("mar/<uuid:pk>/administer/", nurse_views.MARAdministerView.as_view()),
    path("mar/<uuid:pk>/status/", nurse_views.MARStatusView.as_view()),
    path("nurses/<uuid:pk>/tasks/", alias_views.NurseTaskListAliasView.as_view()),
    path("tasks/<uuid:pk>/complete/", nurse_views.TaskCompleteView.as_view()),
    path("handoffs/", nurse_views.HandoffListCreateView.as_view()),
    path("patients/<uuid:patient_id>/discharge-checklist/", nurse_views.DischargeChecklistView.as_view()),
    path("patients/<uuid:patient_id>/discharge-checklist/<uuid:pk>/", nurse_views.DischargeChecklistItemView.as_view()),
]
