# Generated by Django 5.0.6 on 2026-03-27 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDSSRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_module', models.CharField(choices=[('doctor', 'Doctor'), ('nursing', 'Nursing'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology'), ('emergency', 'Emergency'), ('surgery', 'Surgery'), ('system', 'System')], max_length=30)),
                ('target_roles', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('drug_interaction', 'Drug Interaction'), ('allergy', 'Allergy'), ('dosage_warning', 'Dosage Warning'), ('duplicate_therapy', 'Duplicate Therapy'), ('contraindication', 'Contraindication'), ('guideline', 'Guideline'), ('order_set', 'Order Set'), ('appropriateness_check', 'Appropriateness Check'), ('diagnostic', 'Diagnostic'), ('abnormal_result', 'Abnormal Result'), ('panic_value', 'Panic Value'), ('delta_check', 'Delta Check'), ('critical_result', 'Critical Result'), ('preventive', 'Preventive'), ('care_gap', 'Care Gap'), ('follow_up_reminder', 'Follow-up Reminder'), ('deterioration_alert', 'Deterioration Alert'), ('overdue_task', 'Overdue Task'), ('risk_score', 'Risk Score'), ('urgent_finding', 'Urgent Finding'), ('triage_support', 'Triage Support'), ('sepsis_alert', 'Sepsis Alert'), ('trauma_alert', 'Trauma Alert'), ('perioperative_warning', 'Perioperative Warning'), ('checklist_gap', 'Checklist Gap'), ('care_plan_deviation', 'Care Plan Deviation')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('overridden', 'Overridden'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('followed', 'Followed')], default='active', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('triggered_by', models.CharField(max_length=200)),
                ('affected_medications', models.JSONField(default=list)),
                ('suggested_actions', models.JSONField(default=list)),
                ('explanation', models.JSONField(default=dict)),
                ('evidence_sources', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('override_reason_category', models.CharField(blank=True, max_length=100, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_recommendations', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdss_recommendations', to='doctors.encounter')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_recommendations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdss_recommendations', to='patients.patient')),
            ],
            options={
                'db_table': 'cdss_recommendations',
            },
        ),
        migrations.CreateModel(
            name='CDSSOverrideRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('override', 'Override'), ('acknowledge', 'Acknowledge'), ('dismiss', 'Dismiss'), ('follow', 'Follow')], max_length=20)),
                ('reason_category', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('clinician_name', models.CharField(max_length=200)),
                ('clinician_role', models.CharField(max_length=30)),
                ('source_module', models.CharField(blank=True, max_length=30, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_records', to='cdss.cdssrecommendation')),
            ],
            options={
                'db_table': 'cdss_override_records',
            },
        ),
        migrations.AddIndex(
            model_name='cdssrecommendation',
            index=models.Index(fields=['patient', 'status'], name='cdss_recomm_patient_ff11a6_idx'),
        ),
        migrations.AddIndex(
            model_name='cdssrecommendation',
            index=models.Index(fields=['severity', 'status'], name='cdss_recomm_severit_80aa66_idx'),
        ),
        migrations.AddIndex(
            model_name='cdssrecommendation',
            index=models.Index(fields=['type'], name='cdss_recomm_type_d0a6ef_idx'),
        ),
    ]
