# Generated by Django 5.0.6 on 2026-03-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdss", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cdssoverriderecord",
            options={"verbose_name": "CDSS Alert Response", "verbose_name_plural": "CDSS Alert Responses"},
        ),
        migrations.AlterModelOptions(
            name="cdssrecommendation",
            options={"verbose_name": "CDSS Alert", "verbose_name_plural": "CDSS Alerts"},
        ),
    ]
