# Generated by Codex on 2026-04-06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdss", "0002_alter_cdssoverriderecord_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CDSSConsultRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clinical_question", models.TextField()),
                ("context_notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("answered", "Answered"), ("cancelled", "Cancelled")], default="open", max_length=20)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("encounter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cdss_consult_requests", to="doctors.encounter")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cdss_consult_requests", to="patients.patient")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cdss_consult_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "cdss_consult_requests",
                "verbose_name": "CDSS Support Request",
                "verbose_name_plural": "CDSS Support Requests",
            },
        ),
        migrations.AddField(
            model_name="cdssrecommendation",
            name="consult_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_recommendations", to="cdss.cdssconsultrequest"),
        ),
        migrations.AddField(
            model_name="cdssrecommendation",
            name="output_kind",
            field=models.CharField(choices=[("alert", "Alert"), ("recommendation", "Recommendation")], default="alert", max_length=20),
        ),
        migrations.AddIndex(
            model_name="cdssconsultrequest",
            index=models.Index(fields=["patient", "status"], name="cdss_consul_patient_d3bbaa_idx"),
        ),
        migrations.AddIndex(
            model_name="cdssconsultrequest",
            index=models.Index(fields=["status"], name="cdss_consul_status_33d223_idx"),
        ),
        migrations.AddIndex(
            model_name="cdssrecommendation",
            index=models.Index(fields=["output_kind"], name="cdss_recomm_output__38148b_idx"),
        ),
    ]
