# Generated by Django 5.0.6 on 2026-04-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdss', '0003_expand_cdss_outputs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdssrecommendation',
            options={'verbose_name': 'CDSS Insight', 'verbose_name_plural': 'CDSS Insights'},
        ),
        migrations.RenameIndex(
            model_name='cdssconsultrequest',
            new_name='cdss_consul_patient_c8ca9f_idx',
            old_name='cdss_consul_patient_d3bbaa_idx',
        ),
        migrations.RenameIndex(
            model_name='cdssconsultrequest',
            new_name='cdss_consul_status_dd5d3f_idx',
            old_name='cdss_consul_status_33d223_idx',
        ),
        migrations.RenameIndex(
            model_name='cdssrecommendation',
            new_name='cdss_recomm_output__1f162f_idx',
            old_name='cdss_recomm_output__38148b_idx',
        ),
    ]
