# Generated by Django 5.0.6 on 2026-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdss', '0004_alter_cdssrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdssrecommendation',
            name='snomed_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cdssrecommendation',
            name='snomed_display',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
