# Generated by Django 5.0.6 on 2026-04-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdss', '0007_seed_sample_ontology_catalog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalontologyconcept',
            new_name='medical_ont_code_sy_a57776_idx',
            old_name='medical_ont_code_sy_7bf7b3_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalontologyconcept',
            new_name='medical_ont_domain_7b8727_idx',
            old_name='medical_ont_domain_8d19ab_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalontologymapping',
            new_name='medical_ont_source__a065dc_idx',
            old_name='medical_ont_source__fdb18b_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalontologymapping',
            new_name='medical_ont_domain_cc8147_idx',
            old_name='medical_ont_domain_7087d6_idx',
        ),
    ]
