# Generated by Django 5.0.6 on 2026-04-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdss', '0008_rename_medical_ont_code_sy_7bf7b3_idx_medical_ont_code_sy_a57776_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalontologyconcept',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalontologymapping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
