# Generated by Django 5.0.6 on 2026-03-27 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('icu', 'ICU'), ('isolation', 'Isolation'), ('bariatric', 'Bariatric'), ('pediatric', 'Pediatric'), ('day-surgery', 'Day Surgery'), ('recovery', 'Recovery')], default='standard', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('clinical', 'Clinical'), ('diagnostic', 'Diagnostic'), ('surgical', 'Surgical'), ('emergency', 'Emergency'), ('administrative', 'Administrative'), ('support', 'Support')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('specimen', models.CharField(max_length=100)),
                ('turnaround_hours', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_auth', models.BooleanField(default=False)),
                ('cpt_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_catalog',
            },
        ),
        migrations.CreateModel(
            name='RadiologyCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('modality', models.CharField(max_length=20)),
                ('body_part', models.CharField(max_length=100)),
                ('with_contrast', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_auth', models.BooleanField(default=False)),
                ('cpt_code', models.CharField(blank=True, max_length=20, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'radiology_catalog',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=30)),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_catalog',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('category', models.CharField(default='general', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('icu-cardiac', 'ICU Cardiac'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('surgery', 'Surgery'), ('emergency', 'Emergency'), ('step-down', 'Step Down')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('floor_number', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_role', models.CharField(blank=True, max_length=30, null=True)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('resource', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=20)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['resource', 'timestamp'], name='audit_logs_resourc_fdd6d6_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
    ]
