# Generated by Django 5.0.6 on 2026-03-27 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(choices=[('XR', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('PET', 'PET Scan'), ('DEXA', 'DEXA'), ('FLUORO', 'Fluoroscopy'), ('MAMMO', 'Mammography')], max_length=10)),
                ('exam_code', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_name', models.CharField(blank=True, max_length=200, null=True)),
                ('body_part', models.CharField(max_length=200)),
                ('indication', models.TextField()),
                ('clinical_history', models.TextField(blank=True, null=True)),
                ('laterality', models.CharField(blank=True, max_length=30, null=True)),
                ('contrast_required', models.BooleanField(default=False)),
                ('priority', models.CharField(default='routine', max_length=20)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('protocoled', 'Protocoled'), ('scheduled', 'Scheduled'), ('arrived', 'Arrived'), ('in-progress', 'In Progress'), ('acquired', 'Acquired'), ('reading', 'Reading'), ('reported', 'Reported'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('accession_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('protocol_notes', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_room', models.CharField(blank=True, max_length=50, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_radiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_rad_orders', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='patients.patient')),
                ('protocoled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocoled_orders', to=settings.AUTH_USER_MODEL)),
                ('technologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_imaging_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imaging_orders',
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('protocoled', 'Protocoled'), ('scheduled', 'Scheduled'), ('arrived', 'Arrived'), ('in-progress', 'In Progress'), ('acquired', 'Acquired'), ('reading', 'Reading'), ('reported', 'Reported'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('images_count', models.PositiveIntegerField(blank=True, null=True)),
                ('series_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pacs_url', models.URLField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='radiology.imagingorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='patients.patient')),
            ],
            options={
                'db_table': 'imaging_studies',
            },
        ),
        migrations.CreateModel(
            name='ModalitySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(choices=[('XR', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('PET', 'PET Scan'), ('DEXA', 'DEXA'), ('FLUORO', 'Fluoroscopy'), ('MAMMO', 'Mammography')], max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('exam_name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'db_table': 'modality_schedule',
            },
        ),
        migrations.CreateModel(
            name='RadCriticalFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.TextField()),
                ('severity', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged')], default='identified', max_length=20)),
                ('notified_to', models.CharField(blank=True, max_length=200, null=True)),
                ('callback_number', models.CharField(blank=True, max_length=30, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_rad_criticals', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_rad_criticals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rad_critical_findings', to='patients.patient')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_findings', to='radiology.imagingstudy')),
            ],
            options={
                'db_table': 'rad_critical_findings',
            },
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indication', models.TextField()),
                ('technique', models.TextField(blank=True)),
                ('comparison', models.TextField(blank=True, null=True)),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('addendum', 'Addendum'), ('void', 'Void')], default='draft', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('addendum', models.TextField(blank=True, null=True)),
                ('addendum_at', models.DateTimeField(blank=True, null=True)),
                ('addendum_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rad_report_addendums', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='patients.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_rad_reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='radiology.imagingstudy')),
            ],
            options={
                'db_table': 'radiology_reports',
            },
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['patient', 'status'], name='imaging_ord_patient_3f54f2_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['modality'], name='imaging_ord_modalit_6e1c88_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['patient', 'status'], name='imaging_stu_patient_64373f_idx'),
        ),
        migrations.AddIndex(
            model_name='modalityschedule',
            index=models.Index(fields=['date', 'modality', 'room'], name='modality_sc_date_3b62ee_idx'),
        ),
        migrations.AddIndex(
            model_name='radcriticalfinding',
            index=models.Index(fields=['patient', 'status'], name='rad_critica_patient_edd56f_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyreport',
            index=models.Index(fields=['patient', 'status'], name='radiology_r_patient_ca9db1_idx'),
        ),
    ]
