# Generated by Django 5.0.6 on 2026-06-17 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0006_alter_imagingorder_indication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_number', models.PositiveIntegerField(default=1)),
                ('series_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('modality', models.CharField(blank=True, max_length=10, null=True)),
                ('body_part', models.CharField(blank=True, max_length=100, null=True)),
                ('slice_count', models.PositiveIntegerField(default=0)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_series', to='radiology.imagingstudy')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dicom_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dicom_series',
                'ordering': ['-created_at'],
                'unique_together': {('study', 'series_number')},
            },
        ),
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('instance_number', models.PositiveIntegerField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='radiology.dicomseries')),
            ],
            options={
                'db_table': 'dicom_files',
                'ordering': ['instance_number', 'created_at'],
            },
        ),
    ]
