import json
import logging
from urllib import error, request

from apps.cdss.services.graph_service import GraphService

logger = logging.getLogger(__name__)


def context_sentences(text: str):
    return [line for line in text.split("\n") if line.strip().startswith("-")]


class AIService:
    @staticmethod
    def generate_cdss_recommendation(patient_uuid: str, prompt_query: str) -> str:
        """
        Uses GraphRAG to gather patient context from Neo4j and injects it
        into the LLM prompt. Simulates the actual LLM generation.
        """
        # 1. Fetch exact patient subgraph as medical grounding context
        graph_context = GraphService.get_patient_subgraph_context(patient_uuid)

        # 2. Construct the full prompt (GraphRAG approach)
        system_prompt = (
            "You are an expert Clinical Decision Support System (CDSS) AI. "
            "You must use the provided Knowledge Graph Context below to ground your recommendations. "
            "Do not hallucinate conditions the patient does not have.\n\n"
            f"{graph_context}\n\n"
            f"Doctor Query: {prompt_query}"
        )

        logger.info(f"Dispatching query to MedGemma with context length: {len(graph_context)}")

        # 3. Actual API call to the external inference server
        from django.conf import settings

        llm_url = getattr(settings, "LLM_API_URL", "http://host.docker.internal:11434/api/generate")
        model_name = getattr(settings, "LLM_MODEL_NAME", "medllama2")
        llm_timeout = getattr(settings, "LLM_API_TIMEOUT_SECONDS", 30)

        payload = {
            "model": model_name,
            "prompt": system_prompt,
            "stream": False,
        }

        try:
            req = request.Request(
                llm_url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with request.urlopen(req, timeout=llm_timeout) as response:
                result = json.loads(response.read().decode("utf-8"))
                final_response = result.get("response", "[Error: No response generated by local LLM]")

        except error.HTTPError as exc:
            response_body = exc.read().decode("utf-8", errors="replace")
            logger.error("Local LLM returned HTTP %s from %s: %s", exc.code, llm_url, response_body)
            final_response = (
                "[Grounded AI Recommendation Unavailable]\n"
                f"Tried reaching: {llm_url}\n"
                f"Model: {model_name}\n"
                f"Remote server returned HTTP {exc.code}.\n"
                "Check that the remote inference API path and model name match the server configuration."
            )
        except error.URLError as exc:
            logger.error("Failed to connect to local LLM at %s: %s", llm_url, exc)
            final_response = (
                "[Grounded AI Recommendation Unavailable]\n"
                f"Tried reaching: {llm_url}\n"
                f"Model: {model_name}\n\n"
                f"Context analyzed: {len(context_sentences(graph_context))} known relationships.\n"
                "Please ensure the remote inference server is reachable from the backend host and that its port is open."
            )
        except Exception as exc:
            logger.exception("Unexpected LLM integration failure for %s", llm_url)
            final_response = (
                "[Grounded AI Recommendation Unavailable]\n"
                f"Tried reaching: {llm_url}\n"
                f"Model: {model_name}\n\n"
                f"Unexpected integration error: {exc}"
            )

        return final_response
