# Generated by Django 5.0.6 on 2026-03-27 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_checklist', to='patients.patient')),
            ],
            options={
                'db_table': 'discharge_checklist',
                'indexes': [models.Index(fields=['patient'], name='discharge_c_patient_68f4cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(max_length=20)),
                ('situation', models.TextField()),
                ('background', models.TextField()),
                ('assessment', models.TextField()),
                ('recommendation', models.TextField()),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('from_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_given', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='patients.patient')),
                ('to_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_received', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.ward')),
            ],
            options={
                'db_table': 'handoffs',
                'indexes': [models.Index(fields=['ward', 'shift_date', 'shift_type'], name='handoffs_ward_id_04b43b_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntakeOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('intake', 'Intake'), ('output', 'Output')], max_length=10)),
                ('type', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV'), ('ng', 'NG'), ('blood-product', 'Blood Product'), ('irrigation', 'Irrigation'), ('urine', 'Urine'), ('emesis', 'Emesis'), ('drain', 'Drain'), ('stool', 'Stool'), ('blood-loss', 'Blood Loss')], max_length=20)),
                ('amount_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intake_output',
                'indexes': [models.Index(fields=['patient', 'created_at'], name='intake_outp_patient_61e25e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MAREntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('held', 'Held'), ('refused', 'Refused'), ('missed', 'Missed'), ('not-applicable', 'Not Applicable')], default='scheduled', max_length=20)),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mar_administered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='patients.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='doctors.prescription')),
            ],
            options={
                'db_table': 'mar_entries',
                'indexes': [models.Index(fields=['patient', 'scheduled_time'], name='mar_entries_patient_93bbe7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('assessment', 'Assessment'), ('intervention', 'Intervention'), ('education', 'Education'), ('communication', 'Communication'), ('general', 'General')], max_length=30)),
                ('content', models.TextField()),
                ('edit_deadline', models.DateTimeField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='patients.patient')),
            ],
            options={
                'db_table': 'nursing_notes',
                'indexes': [models.Index(fields=['patient', 'created_at'], name='nursing_not_patient_0d704d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PainAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('intervention', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_assessments', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pain_assessments',
                'indexes': [models.Index(fields=['patient', 'created_at'], name='pain_assess_patient_976eed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_time', models.DateTimeField()),
                ('shift', models.CharField(blank=True, max_length=20, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='patients.patient')),
            ],
            options={
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['patient', 'status'], name='tasks_patient_8168e9_idx'), models.Index(fields=['assigned_to', 'status'], name='tasks_assigne_801c9d_idx'), models.Index(fields=['due_time'], name='tasks_due_tim_f4d637_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('pain_score', models.PositiveIntegerField(blank=True, null=True)),
                ('gcs', models.PositiveIntegerField(blank=True, null=True)),
                ('news2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vitals',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'recorded_at'], name='vitals_patient_737668_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('pressure-injury', 'Pressure Injury'), ('surgical', 'Surgical'), ('traumatic', 'Traumatic'), ('diabetic', 'Diabetic'), ('vascular', 'Vascular'), ('moisture-associated', 'Moisture Associated'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('care', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wounds',
                'indexes': [models.Index(fields=['patient'], name='wounds_patient_0bbd1a_idx')],
            },
        ),
    ]
