# Generated by Django 5.0.6 on 2026-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='is_admission_vitals',
            field=models.BooleanField(default=False, help_text='True when this is the baseline vitals recorded at the time of admission.'),
        ),
    ]
