# Generated by Django 5.0.6 on 2026-03-27 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('billed_insurance', 'Billed Insurance'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('cleared', 'Cleared'), ('void', 'Void')], default='draft', max_length=30)),
                ('insurance_plan', models.JSONField(blank=True, default=dict)),
                ('charge_items', models.JSONField(default=list)),
                ('primary_diagnosis', models.CharField(blank=True, max_length=500, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patient_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('void_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient')),
                ('void_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_id', models.CharField(max_length=100)),
                ('claim_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('under-review', 'Under Review'), ('paid', 'Paid'), ('partially-paid', 'Partially Paid'), ('denied', 'Denied'), ('appealed', 'Appealed'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('allowed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('patient_responsibility', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eob_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='patients.patient')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='billing.invoice')),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('credit-card', 'Credit Card'), ('debit-card', 'Debit Card'), ('ach', 'ACH'), ('insurance', 'Insurance'), ('write-off', 'Write-Off'), ('adjustment', 'Adjustment')], max_length=20)),
                ('payer', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('voided', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.claim')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Denial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('missing-info', 'Missing Info'), ('medical-necessity', 'Medical Necessity'), ('auth-required', 'Auth Required'), ('timely-filing', 'Timely Filing'), ('duplicate', 'Duplicate'), ('eligibility', 'Eligibility'), ('coding-error', 'Coding Error'), ('out-of-network', 'Out of Network'), ('other', 'Other')], max_length=30)),
                ('reason_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-review', 'In Review'), ('appealed', 'Appealed'), ('overturned', 'Overturned'), ('upheld', 'Upheld'), ('write-off', 'Write-Off')], default='open', max_length=20)),
                ('appeal_notes', models.TextField(blank=True, null=True)),
                ('appeal_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denials', to='billing.claim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denials', to='patients.patient')),
            ],
            options={
                'db_table': 'denials',
                'indexes': [models.Index(fields=['patient', 'status'], name='denials_patient_186255_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'status'], name='invoices_patient_a03621_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient', 'status'], name='claims_patient_ec809f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'posted_at'], name='payments_invoice_0390e0_idx'),
        ),
    ]
