# Generated by Django 5.0.6 on 2026-04-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtokenrecord',
            options={'verbose_name': 'Refresh token record', 'verbose_name_plural': 'Refresh token records'},
        ),
    ]
