# Generated by Django 5.0.6 on 2026-03-27 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('drug_class', models.CharField(max_length=100)),
                ('formulary_status', models.CharField(choices=[('formulary', 'On Formulary'), ('non-formulary', 'Non-Formulary'), ('restricted', 'Restricted')], default='formulary', max_length=20)),
                ('stock_level', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('unit', models.CharField(default='tablet', max_length=50)),
                ('ndc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'formulary',
            },
        ),
        migrations.CreateModel(
            name='PharmacyPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('pending-verification', 'Pending Verification'), ('verified', 'Verified'), ('dispensing', 'Dispensing'), ('dispensed', 'Dispensed'), ('on-hold', 'On Hold'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending-verification', max_length=30)),
                ('setting', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('discharge', 'Discharge')], default='inpatient', max_length=20)),
                ('priority', models.CharField(default='routine', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity_dispensed', models.PositiveIntegerField(blank=True, null=True)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('drug_warnings', models.JSONField(default=list)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('original_prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_record', to='doctors.prescription')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prescriptions', to='patients.patient')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PharmacyIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('therapy-change', 'Therapy Change'), ('dose-adjustment', 'Dose Adjustment'), ('drug-discontinuation', 'Drug Discontinuation'), ('allergy-clarification', 'Allergy Clarification'), ('brand-to-generic', 'Brand to Generic'), ('formulary-substitution', 'Formulary Substitution'), ('other', 'Other')], max_length=30)),
                ('reason', models.TextField()),
                ('recommendation', models.TextField()),
                ('prescriber_contact', models.CharField(max_length=200)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('prescriber_response', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_interventions', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='pharmacy.pharmacyprescription')),
            ],
            options={
                'db_table': 'pharmacy_interventions',
            },
        ),
        migrations.CreateModel(
            name='DrugWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('interaction', 'Drug Interaction'), ('allergy', 'Allergy'), ('duplication', 'Duplication'), ('dose-range', 'Dose Range'), ('renal', 'Renal'), ('pregnancy', 'Pregnancy'), ('pediatric', 'Pediatric')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('message', models.TextField()),
                ('medications_involved', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_warnings', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='pharmacy.pharmacyprescription')),
            ],
            options={
                'db_table': 'drug_warnings',
            },
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('days_supply', models.PositiveIntegerField(blank=True, null=True)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='pharmacy.pharmacyprescription')),
            ],
            options={
                'db_table': 'dispense_records',
            },
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('days_supply', models.PositiveIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='pharmacy.pharmacyprescription')),
            ],
            options={
                'db_table': 'refills',
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substitute_medication', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_substitutions', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='pharmacy.pharmacyprescription')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_substitutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'substitutions',
            },
        ),
        migrations.AddIndex(
            model_name='pharmacyprescription',
            index=models.Index(fields=['patient', 'status'], name='pharmacy_pr_patient_59e7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='drugwarning',
            index=models.Index(fields=['patient', 'severity'], name='drug_warnin_patient_224bb2_idx'),
        ),
    ]
