# Generated by Django 5.0.6 on 2026-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_formularyitem_rxnorm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularyitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
