# Generated by Django 5.0.6 on 2026-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_order_structured_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="visit_type",
            field=models.CharField(
                choices=[("inpatient", "Inpatient"), ("outpatient", "Outpatient")],
                max_length=20,
            ),
        ),
    ]

