# Generated by Django 5.0.6 on 2026-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_prescription_rxnorm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='snomed_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='snomed_display',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
