# Generated by Django 5.0.6 on 2026-03-27 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resulted', 'Resulted'), ('verified', 'Verified'), ('released', 'Released')], default='pending', max_length=20)),
                ('priority', models.CharField(default='routine', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('has_critical', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_panels', to='doctors.order')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_panels', to='patients.patient')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_panels',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('blood', 'Blood'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('urine', 'Urine'), ('csf', 'CSF'), ('stool', 'Stool'), ('swab', 'Swab'), ('tissue', 'Tissue'), ('other', 'Other')], max_length=20)),
                ('tube_type', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Collected'), ('in-transit', 'In Transit'), ('received', 'Received'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('resulted', 'Resulted'), ('rejected', 'Rejected'), ('recollect', 'Recollect Required')], default='ordered', max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('acceptable', 'Acceptable'), ('hemolyzed', 'Hemolyzed'), ('lipemic', 'Lipemic'), ('icteric', 'Icteric'), ('clotted', 'Clotted'), ('insufficient', 'Insufficient'), ('wrong-tube', 'Wrong Tube')], max_length=20, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('recollect_reason', models.TextField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_specimens', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='doctors.order')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='patients.patient')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_specimens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'specimens',
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_code', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(blank=True, choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('critical-high', 'Critical High'), ('critical-low', 'Critical Low')], max_length=20, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('previous_value', models.CharField(blank=True, max_length=200, null=True)),
                ('delta', models.CharField(blank=True, max_length=100, null=True)),
                ('delta_flag', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('verified', 'Verified'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labpanel')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.specimen')),
            ],
            options={
                'db_table': 'lab_test_results',
            },
        ),
        migrations.AddField(
            model_name='labpanel',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='laboratory.specimen'),
        ),
        migrations.CreateModel(
            name='AnalyzerQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_queue_entries', to='laboratory.specimen')),
            ],
            options={
                'db_table': 'analyzer_queue',
            },
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('condition', models.CharField(choices=[('acceptable', 'Acceptable'), ('hemolyzed', 'Hemolyzed'), ('lipemic', 'Lipemic'), ('icteric', 'Icteric'), ('clotted', 'Clotted'), ('insufficient', 'Insufficient'), ('wrong-tube', 'Wrong Tube')], max_length=20)),
                ('test_names', models.JSONField(default=list)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessioned_specimens', to=settings.AUTH_USER_MODEL)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accession', to='laboratory.specimen')),
            ],
            options={
                'db_table': 'accessions',
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_critical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('released', 'Released'), ('corrected', 'Corrected'), ('amended', 'Amended')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('correction_note', models.TextField(blank=True, null=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('attachment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='laboratory.labpanel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_reports',
                'indexes': [models.Index(fields=['patient', 'status'], name='lab_reports_patient_a9271d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CriticalValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('notified_to', models.CharField(blank=True, max_length=200, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notification_method', models.CharField(blank=True, max_length=50, null=True)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('readback_provided', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_critical_values', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_values', to='patients.patient')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_value', to='laboratory.labtestresult')),
            ],
            options={
                'db_table': 'critical_values',
                'indexes': [models.Index(fields=['patient', 'status'], name='critical_va_patient_a71586_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['patient', 'status'], name='specimens_patient_2a2c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['status'], name='specimens_status_2f518b_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestresult',
            index=models.Index(fields=['panel', 'flag'], name='lab_test_re_panel_i_e58ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestresult',
            index=models.Index(fields=['is_critical'], name='lab_test_re_is_crit_9ca421_idx'),
        ),
        migrations.AddIndex(
            model_name='labpanel',
            index=models.Index(fields=['patient', 'status'], name='lab_panels_patient_e73141_idx'),
        ),
        migrations.AddIndex(
            model_name='labpanel',
            index=models.Index(fields=['status'], name='lab_panels_status_53003b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerqueue',
            index=models.Index(fields=['status'], name='analyzer_qu_status_33abe7_idx'),
        ),
    ]
