# Generated by Django 5.0.6 on 2026-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_sync_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerqueue',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='criticalvalue',
            name='test_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='criticalvalue',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='criticalvalue',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
